@CM
Feature: Community Admin - Create Public HS/HE Only Groups
  As a Community Administrator I want to create Public groups for HS or HE only Community users to join so they
  can have more targeted interactions and discuss topics in a more private manner.

  @MATCH-620
  Scenario: As a Community Administrator I can create Public groups that only HS Community users can join.
    Given SP I am logged in to the Admin page as an Admin user
    Then I navigate to Groups page
    And I click on Add Group button
    Then I populate fields for new Group with name "**AutoGenerated** HS Users Only Group"
    And I select institution type "HS"
    And I click on Create button
    Then I check if group with name "**AutoGenerated** HS Users Only Group" is created

  @MATCH-625
  Scenario: As a Community Administrator I can create Public groups that only HE Community users can join.
    Given SP I am logged in to the Admin page as an Admin user
    Then I navigate to Groups page
    And I click on Add Group button
    Then I populate fields for new Group with name "**AutoGenerated** HE Users Only Group"
    And I select institution type "HE"
    And I click on Create button
    Then I check if group with name "**AutoGenerated** HE Users Only Group" is created

  @MATCH-626
  Scenario: As a non Community Administrator I cannot create a new group.
    Given HE I am logged in to Intersect HE as user type "administrator"
    Then I navigate to Groups page
    And I check if non Community Administrator can create new group
