FROM hobsonspipe/centos-java8:latest

RUN yum -y install maven \
    && yum clean all \
    && mkdir /app

WORKDIR /app
#COPY pom.xml /app

COPY . /app

RUN chmod +x /app/docker/run-tests-Nightly.sh

CMD ["/bin/bash", "/app/docker/run-tests-Nightly.sh"]