@MATCH-433
Feature: Community User - Assign/Remove Custom Categories to Connections
  As a Community user I need to be able to assign custom categories I create to my Community user connections
  so I can more quickly filter and find particular connections on the Manage Connections page.



  @MATCH-434
  Scenario: As a Community user on the Manage Connections page I can assign categories to individual connections one at a time.
    Given HE I am logged in to Intersect HE as user type "administrator"
    And I am connected to HS user
    And I go to connections page
    Then I create new connections category using name "AutogeneratedTestGroup"
    And I add "PurpleHS User" to the "AutogeneratedTestGroup" category
    Then I go to the "AutogeneratedTestGroup" category
    And I check if "PurpleHS User" can be found in the category
    Then I remove all connections from "AutogeneratedTestGroup" category
    Then I delete "AutogeneratedTestGroup" category
    And HE I successfully sign out


#  Cannot assign categories to multiple connections at one time?
#  @MATCH-435
#  Scenario: As a Community user on the Manage Connections page I can assign categories to multiple connections at one time.



  @MATCH-436
  Scenario: As a Community user on the Manage Connections page I can remove categories from individual connections one at a time.
    Given HE I am logged in to Intersect HE as user type "administrator"
    And I am connected to HS user
    And I go to connections page
    Then I create new connections category using name "AutogeneratedTestGroup"
    And I add "PurpleHS User" to the "AutogeneratedTestGroup" category
    And I go to connections page
    Then And I remove "PurpleHS User" from the "AutogeneratedTestGroup" category
    Then I go to the "AutogeneratedTestGroup" category
    And I check if "PurpleHS User" cannot be found in the category
    Then I remove all connections from "AutogeneratedTestGroup" category
    Then I delete "AutogeneratedTestGroup" category
    And HE I successfully sign out


#  Cannot assign categories to multiple connections at one time?
#  @MATCH-437
#  Scenario: As a Community user on the Manage Connections page I can remove categories from multiple connections at one time.

