package pageObjects.CM.userProfilePage;

import org.apache.log4j.Logger;
import org.junit.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebElement;
import pageObjects.CM.commonPages.PageObjectFacadeImpl;

/**
 * Created by bojan on 6/1/17.
 */
public class UserProfilePageImpl extends PageObjectFacadeImpl {

    private Logger logger;


    public UserProfilePageImpl()  {
        logger = Logger.getLogger(UserProfilePageImpl.class);}

    public void iframeEnter()  {
        driver.switchTo().frame(driver.findElement(By.cssSelector("iframe[title=Community]")));
    }

    public void iframeExit() {
        driver.switchTo().defaultContent();
    }

    public void goToUserProfilePage() {
        logger.info("Going to user profile page.");
        link(By.id("js-main-nav-counselor-community-menu-link")).click();
        iframeEnter();
        link(By.cssSelector("a[href='/profile']")).click();
    }

    public void createNewUserPost() {
        logger.info("Creating new user post.");
        newPostTextbox().sendKeys("This post is generated by TestAutomation USER!");
        driver.findElement(By.id("edit-save")).click();
    }

    public void createNewFeedPost() {
        logger.info("Creating new user post.");
        newPostTextbox().sendKeys("Autogenerated test post.");
        driver.findElement(By.id("edit-save")).click();
    }

    public void checkIfUserPostIsCreated() {
        logger.info("Checking if user post is created");
        Assert.assertTrue(driver.findElement(By.xpath("//*[contains(text(), 'This post is generated by TestAutomation USER!')]")).isDisplayed());
        deleteCreatedPost();
    }

    public void deleteCreatedPost() {
        logger.info("Deleting created user post.");
        driver.findElement(By.linkText("edit")).click();
        driver.findElement(By.id("edit-delete")).click();
        waitUntilElementExists(driver.findElement(By.id("edit-delete--3")));
        driver.findElement(By.id("edit-delete--3")).click();
    }

    public void checkIfProfilePostsAreVisible(){
        logger.info("Checking if there are posts on the Profile page");

        try {
            profilePicOnPostsFeed();
        } catch (NoSuchElementException e) {
            createNewFeedPost();
        }

        Assert.assertTrue(profilePicOnPostsFeed().isDisplayed());
    }

    private WebElement newPostTextbox() {
        return driver.findElement(By.id("edit-body"));
    }
    private WebElement profilePicOnPostsFeed() {return driver.findElement(By.xpath("//img[contains(@src, 'https://qa.community.hobsons.com/sites/default/files/styles/post_thumbnail/public/')]"));}

}
