@MATCH-1312
  Feature: As a Community user I need to see confirmation popup with warning message that deletion cannot be undone when deleting a previously created post

    Scenario: As a Community user I need to see confirmation popup with warning message
      Given HE I am logged in to Intersect HE as user type "administrator"
      Then I go to user profile page
      And I create new user post with text "This post is generated by TestAutomation USER!--should be deleted"
      And I click on delete button
      Then I check if I can see "Are you sure you want to delete this post?" on the page
      And I check if I can see "Deleting a post is permanent and cannot be undone." on the page
      Then I click cancel deletion button
      And I check if I can see "This post is generated by TestAutomation USER!--should be deleted" on the page
      Then I delete created post
      And I check if post with text "This post is generated by TestAutomation USER!--should be deleted" is deleted
      And HE I successfully sign out