@CM @MATCH-750
Feature: Community User - Manage Created Posts
  As a Community user I want to manage my already created posts so I can correct any typos or delete posts I no
  longer want to show in the Community.


  @MATCH-755
  Scenario: As a Community user I need the ability to edit a post I have already created.
    Given HE I am logged in to Intersect HE as user type "administrator"
    Then I go to user profile page
    And I create new user post with text "This post is generated by TestAutomation USER!"
    Then I edit post with text "--EDITED-- This post is generated by TestAutomation USER!"
    And I check if user post is created with text "--EDITED-- This post is generated by TestAutomation USER!"
    Then HE I successfully sign out


  @MATCH-756
  Scenario: As a Community institution I need the ability to edit a post I have already created.
    Given HE I am logged in to Intersect HE as user type "administrator"
    And I go to institution page
    And I create new institution post with text "This post is generated by TestAutomation INSTITUTION!"
    Then I edit post with text "--EDITED-- This post is generated by TestAutomation INSTITUTION!"
    And I check if institution post is created with text "--EDITED-- This post is generated by TestAutomation INSTITUTION!"
    Then HE I successfully sign out



  @MATCH-757
  Scenario: As a Community user I need the ability to delete a post I have already created.
    Given HE I am logged in to Intersect HE as user type "administrator"
    Then I go to user profile page
    And I create new user post with text "This post is generated by TestAutomation USER!--should be deleted"
    And I check if the post is created with text "This post is generated by TestAutomation USER!--should be deleted"
    Then I delete created post
    And I check if post with text "This post is generated by TestAutomation USER!--should be deleted" is deleted
    And HE I successfully sign out



  #This scenario is duplicate of MATCH-756
#  @MATCH-758
#  Scenario: As a Community institution I need the ability to edit a post I have already created.



  @MATCH-759
  Scenario: As a Community user that has deleted a post I want the Community to also remove that post from any feeds.
    Given HE I am logged in to Intersect HE as user type "administrator"
    Then I go to user profile page
    And I create new user post with text "This post is generated by TestAutomation USER!--should be deleted from feeds"
    Then I open home tab
    And I check if the post is created with text "This post is generated by TestAutomation USER!--should be deleted from feeds"
    Then I open my profile tab
    And I delete created post
    Then I open home tab
    And I check if post with text "This post is generated by TestAutomation USER!--should be deleted from feeds" is deleted
    Then HE I successfully sign out



  @MATCH-760
  Scenario: As a Community institution that has deleted a post I want the Community to also remove that post from any feeds.
    Given HE I am logged in to Intersect HE as user type "administrator"
    And I go to institution page
    And I create new institution post with text "This post is generated by TestAutomation INSTITUTION!--should be deleted from feeds"
    Then I open home tab
    And I check if the post is created with text "This post is generated by TestAutomation INSTITUTION!--should be deleted from feeds"
    Then I open institution tab
    And I delete created post
    Then I open home tab
    And I check if post with text "This post is generated by TestAutomation INSTITUTION!--should be deleted from feeds" is deleted
    Then HE I successfully sign out