@CM @MATCH-738
Feature: Community User - Post Can Contain Rich Media Content
  As a Community user I can create posts within the community that contain text, hyperlinks, images, videos, and/or documents so my posts are interactable with other Community users.


  @MATCH-739
  Scenario: As a Community user I can create a post that includes a hyperlink.
    Given I am logged in to Purple Community through the HE App
    Then I go to user profile page
    And I create new user post with text "This post is generated by TestAutomation USER!" and hyperlink "https://www.hobsons.com/emea/about"
    Then I check if user post is created with text "This post is generated by TestAutomation USER!" and hyperlink "https://www.hobsons.com/emea/about"
    And I sign out from the HE app


#  This scenario cannot be covered since we do not have a way to select and upload files from 'a' tag. Files can be uploaded only if we use 'input' tag.
#  @MATCH-741
#  Scenario: As a Community user I can create a post that includes a photo.


  @MATCH-743
  Scenario: As a Community user I can create a post that includes a video.
    Given I am logged in to Purple Community through the HE App
    Then I go to user profile page
    And I create new user post with text "This post is generated by TestAutomation USER!" and hyperlink "https://www.youtube.com/watch?v=QIr8Fr4MiqM"
    Then I check if user post is created with text "This post is generated by TestAutomation USER!" and embedded video
    And I sign out from the HE app


#  This scenario cannot be covered since we do not have a way to select and upload files from 'a' tag. Files can be uploaded only if we use 'input' tag.
#  @MATCH-747
#  Scenario: As a Community user I can create a post that includes an uploaded document.
